### ISSUE TITLE
Cannot run on Linux / Ubuntu

### ISSUE THREAD

**Issue by ghost** [JayBrown/nnConv#1]
Running the script on Linux results in the following error:
`./nn-conv.sh: line 11: /usr/bin/sw_vers: No such file or directory`
`sw_vers` being a MacOS component.

**Comment by JayBrown** [comment]
I can't test it, because I don't have Linux, but there's also a version of the script that may work with Linux: https://github.com/JayBrown/nnConv/blob/master/*nix/nn-conv.sh

**Comment by ghost** [comment]
Thank you for the quick reply and apologies. I run the wrong script (the one in the main directory). The one in the `*nix/` seems to do the trick just fine. The issue can be closed.

**Comment by JayBrown** [comment]
No problem. I haven't used it in a long time, and f you find any errors, please let me know. The macOS version might benefit too. :)
